### ISSUE TITLE
Data Values

### ISSUE THREAD

**Issue by batulaiko** [tongplw/Mindwave-Data-Streaming#2]
Do you know what kind of values they are?

I mean low alpha values are between 3000 - 300000 for example, how many Hz or uV, can we understand that and how?

**Comment by tongplw** [comment]
According to [this site](http://eprints.uthm.edu.my/id/eprint/7796/1/NOOR_NADIAH_BT_MOHD_AZALI_24.pdf), typically, power bands are in `volt-squared per Hz` unit. But, the values output from the headband were re-scaled.

You can convert it to a proper unit by `rawValue * 1.8 / 4096 / 2000`
